In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

In [2]:
weather=pd.read_csv('/Users/hurrywish/Downloads/Python_sklearn/【第01部分 核心教程】sklearn深度学习框架入门与实战 3套/02.2019年Scikit-learn的机器学习入门到精通（附讲义、代码、数据集、参考资料） 258课/00.配套资料（代码、讲义、数据等）/00.配套资料（代码、讲义、数据等）/08支持向量机下/weatherAUS5000.csv',index_col=0)

In [3]:
weather.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
0,2015-03-24,Adelaide,12.3,19.3,0.0,5.0,NaN,S,39.0,S,...,19.0,59.0,47.0,1022.2,1021.4,NaN,NaN,15.1,17.7,No
1,2011-07-12,Adelaide,7.9,11.4,0.0,1.0,0.5,N,20.0,NNE,...,7.0,70.0,59.0,1028.7,1025.7,NaN,NaN,8.4,11.3,No
2,2010-02-08,Adelaide,24.0,38.1,0.0,23.4,13.0,SE,39.0,NNE,...,19.0,36.0,24.0,1018.0,1016.0,NaN,NaN,32.4,37.4,No
3,2016-09-19,Adelaide,6.7,16.4,0.4,NaN,NaN,N,31.0,N,...,15.0,65.0,40.0,1014.4,1010.0,NaN,NaN,11.2,15.9,No
4,2014-03-05,Adelaide,16.7,24.8,0.0,6.6,11.7,S,37.0,S,...,24.0,61.0,48.0,1019.3,1018.9,NaN,NaN,20.8,23.7,No

In [4]:
X=weather.iloc[:,:-1]
Y=weather.iloc[:,-1]

In [5]:
X.isnull().sum()/X.shape[0]*100

Date              0.00
Location          0.00
MinTemp           0.42
MaxTemp           0.26
Rainfall          1.00
Evaporation      43.18
Sunshine         48.58
WindGustDir       6.62
WindGustSpeed     6.62
WindDir9am        6.98
WindDir3pm        2.26
WindSpeed9am      1.02
WindSpeed3pm      1.62
Humidity9am       1.28
Humidity3pm       2.40
Pressure9am       9.88
Pressure3pm       9.92
Cloud9am         37.78
Cloud3pm         39.76
Temp9am           0.66
Temp3pm           1.76
dtype: float64

In [6]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8,random_state=0)

In [7]:
x_train.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm'],
      dtype='object')

In [8]:
for i in [x_train,x_test,y_train,y_test]:
    i.reset_index(drop=True,inplace=True)
    
x_train.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm'],
      dtype='object')

In [9]:
y_train.value_counts()

No     3085
Yes     915
Name: RainTomorrow, dtype: int64

In [10]:
y_test.value_counts()

No     776
Yes    224
Name: RainTomorrow, dtype: int64

In [11]:
encoder=LabelEncoder().fit(y_train)
y_train=encoder.transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
x_train.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,3981.0,12.121854,6.364655,-8.5,-1.800,1.800,4.00,7.6,12.0,16.6,20.8,25.700,29.0
MaxTemp,3990.0,23.144185,7.162644,-3.7,8.578,12.845,14.50,17.9,22.6,28.3,33.0,39.811,46.4
Rainfall,3959.0,2.379843,7.887643,0.0,0.000,0.000,0.00,0.0,0.0,0.8,6.0,39.020,115.8
Evaporation,2269.0,5.609696,4.325152,0.0,0.400,0.800,1.40,2.6,4.8,7.4,10.2,20.728,56.0
Sunshine,2045.0,7.558582,3.823647,0.0,0.000,0.300,1.40,4.7,8.4,10.6,12.0,13.400,13.9
WindGustSpeed,3742.0,39.911010,13.450746,9.0,15.000,20.000,24.00,31.0,39.0,48.0,57.0,76.000,122.0
WindSpeed9am,3963.0,14.064850,8.836423,0.0,0.000,0.000,4.00,7.0,13.0,19.0,26.0,39.000,72.0
WindSpeed3pm,3940.0,18.577157,8.629868,0.0,2.000,6.000,7.00,13.0,19.0,24.0,30.0,43.000,61.0
Humidity9am,3947.0,68.819356,18.778109,2.0,18.000,36.000,44.00,57.0,70.0,83.0,94.0,100.000,100.0
Humidity3pm,3904.0,51.452613,20.660756,2.0,9.000,17.000,23.00,37.0,52.0,65.0,78.0,98.000,100.0
Pressure9am,3597.0,1017.675480,7.005034,985.1,1000.996,1006.300,1008.90,1012.9,1017.7,1022.3,1026.8,1033.400,1038.1
Pressure3pm,3594.0,1015.277824,6.993600,980.2,998.586,1004.100,1006.53,1010.5,1015.3,1020.0,1024.3,1031.107,1036.0
Cloud9am,2479.0,4.473981,2.863034,0.0,0.000,0.000,1.00,1.0,5.0,7.0,8.0,8.000,8.0
Cloud3pm,2392.0,4.535535,2.665279,0.0,0.000,0.000,1.00,2.0,5.0,7.0,8.0,8.000,8.0
Temp9am,3972.0,16.909315,6.494242,-5.3,2.200,6.900,9.00,12.2,16.6,21.5,25.7,30.900,35.5
Temp3pm,3929.0,21.661110,6.989553,-4.1,7.184,11.600,13.28,16.5,21.0,26.5,31.3,38.000,45.9

In [13]:
x_test.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
MinTemp,998.0,12.177655,6.497671,-5.3,-2.003,1.570,3.80,7.700,12.0,16.80,20.80,26.206,28.8
MaxTemp,997.0,23.142227,7.045593,0.1,9.200,13.000,14.70,18.000,22.4,28.00,32.44,41.604,44.9
Rainfall,991.0,2.548335,8.252277,0.0,0.000,0.000,0.00,0.000,0.0,0.80,6.80,45.340,91.4
Evaporation,572.0,5.714685,4.204180,0.0,0.542,1.000,1.60,2.800,5.0,7.60,10.18,19.800,32.0
Sunshine,526.0,7.565209,3.824675,0.0,0.000,0.600,1.65,4.500,8.2,10.70,12.20,13.275,13.9
WindGustSpeed,927.0,39.927724,13.537731,13.0,17.000,20.000,24.00,30.000,39.0,48.00,57.00,80.740,106.0
WindSpeed9am,986.0,13.881339,8.695942,0.0,0.000,0.000,4.00,7.000,13.0,20.00,24.00,37.000,67.0
WindSpeed3pm,979.0,18.530133,8.900602,0.0,1.560,6.000,7.00,11.000,19.0,24.00,30.00,44.000,65.0
Humidity9am,989.0,69.497472,18.952403,6.0,20.000,35.000,45.00,58.000,70.0,84.00,95.00,100.000,100.0
Humidity3pm,976.0,52.116803,20.481003,3.0,9.000,18.000,24.00,38.000,53.0,66.00,79.50,97.000,100.0
Pressure9am,909.0,1017.621122,7.075908,995.0,1000.200,1005.700,1008.50,1012.900,1017.6,1022.30,1026.90,1033.184,1038.2
Pressure3pm,910.0,1015.280110,7.018051,995.0,998.781,1003.745,1006.29,1010.525,1015.2,1020.00,1024.32,1030.691,1036.9
Cloud9am,632.0,4.566456,2.858304,0.0,0.000,0.000,1.00,1.000,5.0,7.00,8.00,8.000,8.0
Cloud3pm,620.0,4.570968,2.739609,0.0,0.000,0.000,1.00,2.000,5.0,7.00,8.00,8.000,8.0
Temp9am,995.0,16.955879,6.422454,-1.6,3.482,7.000,9.00,12.300,16.5,21.25,26.30,30.606,38.0
Temp3pm,983.0,21.595829,6.812261,-0.1,8.300,11.700,13.30,16.800,21.0,26.30,31.10,39.218,42.5

In [14]:
x_train['Date'].value_counts()

2013-12-20    7
2017-05-24    6
2015-10-12    6
2017-06-05    6
2012-09-18    6
             ..
2010-10-06    1
2010-05-29    1
2010-11-14    1
2013-05-09    1
2010-03-07    1
Name: Date, Length: 2294, dtype: int64

In [15]:
# del x_train['Date']
# del x_test['Date']

In [16]:
x_train['RainTody']=0
x_train.loc[x_train['Rainfall']>=1,['RainTody']]='Yes'
x_train.loc[x_train['Rainfall']<1,['RainTody']]='No'
x_train.loc[x_train['Rainfall']==np.nan,['RainTody']]=np.nan

x_test['RainTody']=0
x_test.loc[x_test['Rainfall']>=1,['RainTody']]='Yes'
x_test.loc[x_test['Rainfall']<1,['RainTody']]='No'
x_test.loc[x_test['Rainfall']==np.nan,['RainTody']]=np.nan

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/hurrywish/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/hurrywish/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/hurrywish/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/Users/hurrywish/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [20]:
x_train['Date']=pd.DatetimeIndex(x_train['Date']).strftime('%m').astype(np.int)

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [18]:
x_test['Date']=pd.DatetimeIndex(x_test['Date']).strftime('%m').astype(np.int)

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [28]:
x_train.rename(columns={'Date':'Month'},inplace=True)
x_test.rename(columns={'Date':'Month'},inplace=True)

/Users/hurrywish/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4304: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [29]:
x_train

,Month,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTody
0,7,Nuriootpa,6.4,12.2,0.0,2.8,0.2,ENE,39.0,NE,...,19.0,65.0,72.0,1019.1,1013.5,7.0,7.0,8.2,9.9,No
1,3,Perth,15.8,33.8,0.0,10.0,11.7,NE,35.0,ENE,...,9.0,51.0,16.0,1023.8,1019.7,0.0,0.0,20.0,32.8,No
2,5,Bendigo,8.1,16.9,0.0,NaN,NaN,W,28.0,NaN,...,13.0,85.0,50.0,1019.7,1016.7,8.0,8.0,10.9,16.7,No
3,10,Albury,6.2,23.7,0.0,NaN,NaN,SSW,20.0,ESE,...,9.0,63.0,35.0,1023.9,1021.1,NaN,NaN,13.7,22.5,No
4,10,CoffsHarbour,17.2,25.8,1.0,NaN,NaN,NNE,61.0,N,...,46.0,66.0,66.0,1022.2,1017.2,1.0,NaN,22.3,23.6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,10,Woomera,9.0,21.5,0.0,7.8,11.9,SE,35.0,SE,...,15.0,52.0,20.0,1025.6,1024.3,0.0,0.0,12.4,19.9,No
3996,7,Perth,10.6,19.8,0.4,2.2,4.1,WNW,31.0,NaN,...,11.0,87.0,62.0,1024.4,1022.9,7.0,7.0,14.9,18.5,No
3997,5,Hobart,9.8,19.2,7.6,0.8,8.1,NW,43.0,NNW,...,11.0,60.0,49.0,1015.3,1015.8,2.0,6.0,13.9,18.0,Yes
3998,1,Newcastle,20.8,29.2,0.0,NaN,NaN,NaN,NaN,NE,...,28.0,65.0,68.0,NaN,NaN,8.0,1.0,23.8,28.2,No
3999,9,NorahHead,6.8,15.4,0.2,NaN,NaN,SSW,67.0,WSW,...,30.0,50.0,59.0,1021.8,1020.1,NaN,NaN,11.5,15.1,No

In [31]:
x_train['Location'].value_counts()

Bendigo             106
Witchcliffe          99
Ballarat             97
Canberra             97
SalmonGums           96
Wollongong           96
BadgerysCreek        94
Cairns               94
Cobar                92
Moree                92
Darwin               92
Sydney               91
Launceston           91
Townsville           91
Penrith              89
Perth                89
CoffsHarbour         88
Newcastle            87
Albury               86
SydneyAirport        86
Adelaide             86
MelbourneAirport     85
Mildura              85
WaggaWagga           82
NorahHead            82
Hobart               82
MountGambier         81
Richmond             81
Woomera              81
MountGinini          79
Dartmoor             78
GoldCoast            77
Brisbane             77
Watsonia             77
Albany               77
Portland             77
NorfolkIsland        76
PerthAirport         74
Nuriootpa            74
AliceSprings         73
Walpole              72
Sale                 72
Tuggeranong          72
PearceRAAF           70
Williamtown          69
Melbourne            64
Uluru                51
Katherine            50
Nhil                 43
Name: Location, dtype: int64